### ISSUE TITLE
_FrameSeparateWidgetState 的 didUpdateWidget 实现有点疑问

### ISSUE THREAD

**Issue by yrom** [LianjiaTech/keframe#1]
点 `setState增加20`按钮，_FrameSeparateWidgetState didUpdateWidget会被调用，此时 result 有可能已经是 oldWidget 的child，按`分帧渲染`的理论是不是应该再重走一次 initState()中的逻辑? 目前是会先build oldWidget.child 再被transformWidget setState 替换为 widget.child

另外，_SizeCacheWidgetState 里的 NotificationListener 用法有误，泛型加上 LayoutInfoNotification 即可，NotificationListener 在调用 onNotification 时会先判断类型
```diff
@@ -44,15 +44,12 @@ class _SizeCacheWidgetState extends State<SizeCacheWidget> {
   Widget build(BuildContext context) {
     return Builder(
       builder: (ctx) {
-        return NotificationListener(
-          onNotification: (dynamic notification) {
-            if (notification is LayoutInfoNotification) {
-              logcat(
-                  "size info :  index = ${notification.index}  size = ${notification.size.toString()}");
-              saveLayoutInfo(notification.index, notification.size);
-              return true;
-            }
-            return false;
+        return NotificationListener<LayoutInfoNotification> (
+          onNotification: (LayoutInfoNotification notification) {
+            logcat(
+                "size info :  index = ${notification.index}  size = ${notification.size.toString()}");
+            saveLayoutInfo(notification.index, notification.size);
+            return true;
           },
           child: widget.child,
         );
```

**Comment by Nayuta403** [comment]
嗯嗯，假如 didUpdateWidget 中重走一次 initState 的话有两点考虑：
1、整个页面又会出现占位变为实际列表项的过程，直观的来看就是列表加载更多的时候会白一下，感觉没必要那么频繁。
2、如果走 initState 的话，从分帧组件的子节点来看，element 树结构会发生变化，这将导致，即使 oldWidget 和 widget 中的 child 没有变化，但是第二次 child 会再次 mount 到 element 树中，走完完整的生命周期，不确定会不会带来不符合预期的结果。

第二点非常感谢指出，因为不影响功能，所以考虑暂不做版本升级。等下会提交代码，也欢迎 PR

**Comment by Nayuta403** [comment]
第二点已经修改并升级，最新版本 2.0.1
