### ISSUE TITLE
在长列表场景中,当组件被移动到视口外,是不是不会被清除内存

### ISSUE THREAD

**Issue by a1239897580** [LianjiaTech/keframe#16]
使用了本插件后,性能得到了很大的提升,有原本的40+提升到了55+。
但是好像也带来了个新问题,使用了本插件后,在动态(朋友圈)场景下内存爆增,我不清楚是不是我的代码问题还是插件的特性。
通过调试发现好像在item==1的时候,整个列表的组件全部被加载出来了,并且用户通过滑动移动时,item移出视口外内存没有得到释放，用户通过上拉持续获取新的数据,当列表加载至百条时,内存就撑不住了。

**Comment by a1239897580** [comment]
是否可以加一个缓存的item个数上限?超过了就清除以前的缓存新的

**Comment by Nayuta403** [comment]
> 是否可以加一个缓存的item个数上限?超过了就清除以前的缓存新的

item ==1 的时候整个被加载出来可能和你的 ListView 的 cacheExten 设置过大有关，这块的预加载逻辑是 ListView 自身的特性。
缓存 item 上限，如果使用 SizeInfoStoreWidget 可以设置一个最大分帧的 item 数量，不过不确定对你说的问题有没有帮助。

**Comment by Nayuta403** [comment]
> 使用了本插件后,性能得到了很大的提升,有原本的40+提升到了55+。 但是好像也带来了个新问题,使用了本插件后,在动态(朋友圈)场景下内存爆增,我不清楚是不是我的代码问题还是插件的特性。 通过调试发现好像在item==1的时候,整个列表的组件全部被加载出来了,并且用户通过滑动移动时,item移出视口外内存没有得到释放，用户通过上拉持续获取新的数据,当列表加载至百条时,内存就撑不住了。

这个问题你可以是试试在 item 的 dispose 加日志，看看在最底下的时候前面的 item 有没有被释放

**Comment by a1239897580** [comment]
> > 是否可以加一个缓存的item个数上限?超过了就清除以前的缓存新的
> 
> item ==1 的时候整个被加载出来可能和你的 ListView 的 cacheExten 设置过大有关，这块的预加载逻辑是 ListView 自身的特性。 缓存 item 上限，如果使用 SizeInfoStoreWidget 可以设置一个最大分帧的 item 数量，不过不确定对你说的问题有没有帮助。

一开始尝试了设置最大分帧数，没有达到预期效果。例如我现在一页有50条数据。进入该页面的时候，50条item全部渲染出来了，我把最大分帧数那个参数设置为5，滑动列表查看显示的结果是只有最后五个item也就是45，46，47，48，49这几个item正常显示，其余的item全部显示的是占位图widget

**Comment by a1239897580** [comment]
listview我没有设置cacheExten这个参数,刚刚加了dispose确实了item没有被释放。

**Comment by a1239897580** [comment]
I/flutter ( 5292): BKFrame  size info :  index = 0  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 1  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 2  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 3  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 4  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 5  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 6  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 7  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 8  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 9  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 10  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 11  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 12  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 13  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 14  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 15  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 16  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 17  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 18  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 19  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 20  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 21  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 22  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 23  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 24  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 25  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 26  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 27  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 28  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 29  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 30  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 31  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 32  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 33  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 34  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 35  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 36  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 37  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 38  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 39  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 40  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 41  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 42  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 43  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 44  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 45  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 46  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 47  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 48  size = Size(360.0, 96.0)
I/flutter ( 5292): BKFrame  size info :  index = 49  size = Size(360.0, 96.0)
I/flutter ( 5292): viewport : [0,49]
I/flutter ( 5292): BKFrame  remove Task
I/flutter ( 5292): BKFrame  remove Task
I/flutter ( 5292): BKFrame  size info :  index = 45  size = Size(360.0, 178.2)
I/flutter ( 5292): viewport : [0,49]
I/flutter ( 5292): BKFrame  size info :  index = 46  size = Size(360.0, 101.4)
I/flutter ( 5292): viewport : [0,49]
I/flutter ( 5292): BKFrame  size info :  index = 47  size = Size(360.0, 101.4)
I/flutter ( 5292): viewport : [0,49]
I/flutter ( 5292): BKFrame  size info :  index = 48  size = Size(360.0, 101.4)
I/flutter ( 5292): viewport : [0,49]
I/flutter ( 5292): BKFrame  size info :  index = 49  size = Size(360.0, 101.4)
I/flutter ( 5292): viewport : [0,49]
I/flutter ( 5292): BKFrame  size info :  index = 49  size = Size(360.0, 425.9)
I/flutter ( 5292): viewport : [0,49]
I/flutter ( 5292): BKFrame  size info :  index = 46  size = Size(360.0, 425.9)
I/flutter ( 5292): viewport : [0,49]
I/flutter ( 5292): BKFrame  size info :  index = 47  size = Size(360.0, 425.9)
I/flutter ( 5292): viewport : [0,49]
I/flutter ( 5292): BKFrame  size info :  index = 48  size = Size(360.0, 425.9)
I/flutter ( 5292): viewport : [0,49]

进入页面什么都没有操作的打印

**Comment by a1239897580** [comment]
![image](https://user-images.githubusercontent.com/70512922/177255744-12cd6c7f-3e7f-440f-80ea-63ae54fdee10.png)

**Comment by a1239897580** [comment]
我好像发现了问题了，SmartRefresher这个组件的问题，分帧组件和这个组件同时使用发生了冲突，去掉任何一个都可以正常释放，但是两个一起使用就发生了现在这种异常，一次性全部加载出来并且不会被释放。去掉了这个组件的嵌套，就可以正常释放了。但我又不得不使用他，他是列表上拉加载下啦刷新组件，应用内的列表都需要用。

**Comment by a1239897580** [comment]
这个页面的问题解决了,把SizeCacheWidget移动到最外层可以得到解决。
我的理解是SizeCacheWidget应该与FrameSeparateWidget紧邻配套使用的。在上面这个页面简单布局可以放到最外层解决。但是首页的话就没办法了，首页有多个滚动列表的复杂布局，就有点不好处理，不能直接放到最外层了。SizeCacheWidget直接放最上层的话他就包裹了几个列表

**Comment by a1239897580** [comment]
![image](https://user-images.githubusercontent.com/70512922/177259154-0f18cd15-832b-49c2-82fb-e2ae5b05e3fa.png)
这是首页的层级，页面存在多个滚动布局

**Comment by Nayuta403** [comment]
没看到过他的实现，不过可能他里面会有一些缓存相关逻辑
