### ISSUE TITLE
如果有单个ListTile高度大于一个屏幕高度的时候，无法向上滑动加载

### ISSUE THREAD

**Issue by sunjianan9900** [LianjiaTech/keframe#3]
场景是类似贴吧的一个listview，有很多帖子，如果帖子高度不高的话没有问题
但是如果有两篇帖子高度大于屏幕高度，这个时候可以向下滑动加载，但是想返回向上滑的时候就会卡住了。
一只不停的闪动，甚至会反向向下滑动。

如果需要演示视频，可以留一个邮箱，我发给您。

**Comment by sunjianan9900** [comment]
另外还有一个问题，就是加载异常缓慢的问题，已经滑动到下面，但是帖子需要10秒以上才出现。相反向上滑动直接什么也没有了。
这个也有视频

**Comment by Nayuta403** [comment]
ok  可以发到我的邮箱 762579473@qq.com ，尽量描述下关键步骤，如果方便可以附上一些脱敏的关键代码

**Comment by Nayuta403** [comment]
使 1.0.2 或者 2.0.2 版本试试

**Comment by sunjianan9900** [comment]
已经在2.0.2修复
大佬V5
