### ISSUE TITLE
对于被嵌套的widge中含有image时效果不明显

### ISSUE THREAD

**Issue by JH90iOS** [LianjiaTech/keframe#9]
因为image.net是异步加载的，所以即使分帧中调用了setState，image网络图片加载完成后仍会异步的调用Image组件的setState，大量图片加载完成后的调度仍是未分帧的，仍然是卡顿，此时keframe的作用基本没有效果，不知道是不是我的用法不对还是理解有误?

**Comment by Nayuta403** [comment]
是这样的，其实我测试的时候 Image 组件几乎没有很明显的耗时现象，就是理解为他自带分帧的效果

**Comment by JH90iOS** [comment]
> 是这样的，其实我测试的时候 Image 组件几乎没有很明显的耗时现象，就是理解为他自带分帧的效果

感谢回复，keframe可以很好的解决我项目中复杂视图的渲染问题，不过我测试时当滚动列表有大量图加载时候有明显的卡顿，确实不是因为UI耗时，而是大量并发图片网络请求以及解码，造成了CPU使用峰值和内存峰值，这个问题不知道能否指点一下

**Comment by Nayuta403** [comment]
嗯嗯 我们公司其实之前有个方案在这，也开源了，你可以参考一下看看https://mp.weixin.qq.com/s/yUm4UFggYLgDbj4_JCjEdg

**Comment by JH90iOS** [comment]
> 嗯嗯 我们公司其实之前有个方案在这，也开源了，你可以参考一下看看https://mp.weixin.qq.com/s/yUm4UFggYLgDbj4_JCjEdg

好的我研读一下，非常感谢。

**Comment by hpepper0220** [comment]
> 嗯嗯 我们公司其实之前有个方案在这，也开源了，你可以参考一下看看https://mp.weixin.qq.com/s/yUm4UFggYLgDbj4_JCjEdg

你好，我看了文章，写的非常棒👍。但是没有看到开源地址哎？方便发一下吗？
